const EVENTS = {
    USER_JOINED: 'USER_JOINED',
    USER_LEFT: 'USER_LEFT',
    UPDATE_CURSOR_COORDINATES: 'UPDATE_CURSOR_COORDINATES',
    MOVE_CURSOR: 'MOVE_CURSOR',

    CONNECTION: 'connection',
    DISCONNECT: 'disconnect',
}

const SPACE_NAME = 'SHARED_SPACE'

module.exports = {
    SPACE_NAME,
    EVENTS,
}
